/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module ALU (
  input USE_CARRY,
  input C_FLAG,
  input [15:0] RB,
  input [15:0] RA,
  input A2,
  input A0,
  input A1,
  input A3,
  output [15:0] ALU_OUT,
  output CARRY_OUT
);
  wire [15:0] s0;
  wire s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [1:0] s6;
  wire [15:0] s7;
  wire [15:0] s8;
  wire [15:0] s9;
  wire [15:0] s10;
  wire [15:0] s11;
  wire [1:0] s12;
  wire [15:0] s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire [15:0] s28;
  wire [15:0] s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire [15:0] s44;
  wire [15:0] s45;
  assign s3 = (RB & RA);
  assign s4 = (RB | RA);
  assign s5 = (RB ^ RA);
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i0 (
    .sel( A1 ),
    .in_0( RB ),
    .in_1( 16'b1 ),
    .out( s10 )
  );
  Mux_2x1 Mux_2x1_i1 (
    .sel( USE_CARRY ),
    .in_0( A0 ),
    .in_1( C_FLAG ),
    .out( s1 )
  );
  assign s6[0] = A0;
  assign s6[1] = A1;
  assign s12[0] = A2;
  assign s12[1] = A3;
  assign s8[0] = A2;
  assign s8[1] = A2;
  assign s8[2] = A2;
  assign s8[3] = A2;
  assign s8[4] = A2;
  assign s8[5] = A2;
  assign s8[6] = A2;
  assign s8[7] = A2;
  assign s8[8] = A2;
  assign s8[9] = A2;
  assign s8[10] = A2;
  assign s8[11] = A2;
  assign s8[12] = A2;
  assign s8[13] = A2;
  assign s8[14] = A2;
  assign s8[15] = A2;
  assign s11[0] = A0;
  assign s11[1] = A0;
  assign s11[2] = A0;
  assign s11[3] = A0;
  assign s11[4] = A0;
  assign s11[5] = A0;
  assign s11[6] = A0;
  assign s11[7] = A0;
  assign s11[8] = A0;
  assign s11[9] = A0;
  assign s11[10] = A0;
  assign s11[11] = A0;
  assign s11[12] = A0;
  assign s11[13] = A0;
  assign s11[14] = A0;
  assign s11[15] = A0;
  assign s14 = RA[1];
  assign s15 = RA[2];
  assign s16 = RA[3];
  assign s17 = RA[4];
  assign s18 = RA[5];
  assign s19 = RA[6];
  assign s20 = RA[7];
  assign s21 = RA[8];
  assign s22 = RA[9];
  assign s23 = RA[10];
  assign s24 = RA[11];
  assign s25 = RA[12];
  assign s26 = RA[13];
  assign s27 = RA[14];
  assign s30 = RB[1];
  assign s31 = RB[2];
  assign s32 = RB[3];
  assign s33 = RB[4];
  assign s34 = RB[5];
  assign s35 = RB[6];
  assign s36 = RB[7];
  assign s37 = RB[8];
  assign s38 = RB[9];
  assign s39 = RB[10];
  assign s40 = RB[11];
  assign s41 = RB[12];
  assign s42 = RB[13];
  assign s43 = RB[14];
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i2 (
    .sel( s6 ),
    .in_0( s3 ),
    .in_1( s4 ),
    .in_2( s5 ),
    .in_3( RA ),
    .out( s7 )
  );
  assign s0 = (s10 ^ s11);
  assign s28[0] = 1'b0;
  assign s28[1] = RA[0];
  assign s28[2] = s14;
  assign s28[3] = s15;
  assign s28[4] = s16;
  assign s28[5] = s17;
  assign s28[6] = s18;
  assign s28[7] = s19;
  assign s28[8] = s20;
  assign s28[9] = s21;
  assign s28[10] = s22;
  assign s28[11] = s23;
  assign s28[12] = s24;
  assign s28[13] = s25;
  assign s28[14] = s26;
  assign s28[15] = s27;
  assign s29[0] = s14;
  assign s29[1] = s15;
  assign s29[2] = s16;
  assign s29[3] = s17;
  assign s29[4] = s18;
  assign s29[5] = s19;
  assign s29[6] = s20;
  assign s29[7] = s21;
  assign s29[8] = s22;
  assign s29[9] = s23;
  assign s29[10] = s24;
  assign s29[11] = s25;
  assign s29[12] = s26;
  assign s29[13] = s27;
  assign s29[14] = RA[15];
  assign s29[15] = 1'b0;
  assign s44[0] = 1'b0;
  assign s44[1] = RB[0];
  assign s44[2] = s30;
  assign s44[3] = s31;
  assign s44[4] = s32;
  assign s44[5] = s33;
  assign s44[6] = s34;
  assign s44[7] = s35;
  assign s44[8] = s36;
  assign s44[9] = s37;
  assign s44[10] = s38;
  assign s44[11] = s39;
  assign s44[12] = s40;
  assign s44[13] = s41;
  assign s44[14] = s42;
  assign s44[15] = s43;
  assign s45[0] = s30;
  assign s45[1] = s31;
  assign s45[2] = s32;
  assign s45[3] = s33;
  assign s45[4] = s34;
  assign s45[5] = s35;
  assign s45[6] = s36;
  assign s45[7] = s37;
  assign s45[8] = s38;
  assign s45[9] = s39;
  assign s45[10] = s40;
  assign s45[11] = s41;
  assign s45[12] = s42;
  assign s45[13] = s43;
  assign s45[14] = RB[15];
  assign s45[15] = 1'b0;
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i3 (
    .a( RA ),
    .b( s0 ),
    .c_i( s1 ),
    .s( s2 ),
    .c_o( CARRY_OUT )
  );
  assign s9 = (s8 ^ s7);
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i4 (
    .sel( s6 ),
    .in_0( s28 ),
    .in_1( s29 ),
    .in_2( s44 ),
    .in_3( s45 ),
    .out( s13 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i5 (
    .sel( s12 ),
    .in_0( s2 ),
    .in_1( s13 ),
    .in_2( s9 ),
    .in_3( s9 ),
    .out( ALU_OUT )
  );
endmodule
