-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_1 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_1;

architecture Behavioral of MUX_GATE_BUS_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_1 is
  port (
    p_out: out std_logic;
    sel: in std_logic;
    
    in_0: in std_logic;
    in_1: in std_logic );
end MUX_GATE_1;

architecture Behavioral of MUX_GATE_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      '0' when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_2 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic_vector (1 downto 0);
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0);
    in_2: in std_logic_vector ((Bits-1) downto 0);
    in_3: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_2;

architecture Behavioral of MUX_GATE_BUS_2 is
begin
  with sel select
    p_out <=
      in_0 when "00",
      in_1 when "01",
      in_2 when "10",
      in_3 when "11",
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;

entity DIG_Add is
  generic ( Bits: integer ); 
  port (
    s: out std_logic_vector((Bits-1) downto 0);
    c_o: out std_logic;
    a: in std_logic_vector((Bits-1) downto 0);
    b: in std_logic_vector((Bits-1) downto 0);
    c_i: in std_logic );
end DIG_Add;

architecture Behavioral of DIG_Add is
   signal temp : std_logic_vector(Bits downto 0);
begin
   temp <= ('0' & a) + b + c_i;

   s    <= temp((Bits-1) downto 0);
   c_o  <= temp(Bits);
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    USE_CARRY: in std_logic;
    C_FLAG: in std_logic;
    RB: in std_logic_vector(15 downto 0);
    RA: in std_logic_vector(15 downto 0);
    A2: in std_logic;
    A0: in std_logic;
    A1: in std_logic;
    A3: in std_logic;
    ALU_OUT: out std_logic_vector(15 downto 0);
    CARRY_OUT: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic_vector(15 downto 0);
  signal s1: std_logic;
  signal s2: std_logic_vector(15 downto 0);
  signal s3: std_logic_vector(15 downto 0);
  signal s4: std_logic_vector(15 downto 0);
  signal s5: std_logic_vector(15 downto 0);
  signal s6: std_logic_vector(1 downto 0);
  signal s7: std_logic_vector(15 downto 0);
  signal s8: std_logic_vector(15 downto 0);
  signal s9: std_logic_vector(15 downto 0);
  signal s10: std_logic_vector(15 downto 0);
  signal s11: std_logic_vector(15 downto 0);
  signal s12: std_logic_vector(1 downto 0);
  signal s13: std_logic_vector(15 downto 0);
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic;
  signal s17: std_logic;
  signal s18: std_logic;
  signal s19: std_logic;
  signal s20: std_logic;
  signal s21: std_logic;
  signal s22: std_logic;
  signal s23: std_logic;
  signal s24: std_logic;
  signal s25: std_logic;
  signal s26: std_logic;
  signal s27: std_logic;
  signal s28: std_logic_vector(15 downto 0);
  signal s29: std_logic_vector(15 downto 0);
  signal s30: std_logic;
  signal s31: std_logic;
  signal s32: std_logic;
  signal s33: std_logic;
  signal s34: std_logic;
  signal s35: std_logic;
  signal s36: std_logic;
  signal s37: std_logic;
  signal s38: std_logic;
  signal s39: std_logic;
  signal s40: std_logic;
  signal s41: std_logic;
  signal s42: std_logic;
  signal s43: std_logic;
  signal s44: std_logic_vector(15 downto 0);
  signal s45: std_logic_vector(15 downto 0);
begin
  s3 <= (RB AND RA);
  s4 <= (RB OR RA);
  s5 <= (RB XOR RA);
  gate0: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 16)
    port map (
      sel => A1,
      in_0 => RB,
      in_1 => "0000000000000001",
      p_out => s10);
  gate1: entity work.MUX_GATE_1
    port map (
      sel => USE_CARRY,
      in_0 => A0,
      in_1 => C_FLAG,
      p_out => s1);
  s6(0) <= A0;
  s6(1) <= A1;
  s12(0) <= A2;
  s12(1) <= A3;
  s8(0) <= A2;
  s8(1) <= A2;
  s8(2) <= A2;
  s8(3) <= A2;
  s8(4) <= A2;
  s8(5) <= A2;
  s8(6) <= A2;
  s8(7) <= A2;
  s8(8) <= A2;
  s8(9) <= A2;
  s8(10) <= A2;
  s8(11) <= A2;
  s8(12) <= A2;
  s8(13) <= A2;
  s8(14) <= A2;
  s8(15) <= A2;
  s11(0) <= A0;
  s11(1) <= A0;
  s11(2) <= A0;
  s11(3) <= A0;
  s11(4) <= A0;
  s11(5) <= A0;
  s11(6) <= A0;
  s11(7) <= A0;
  s11(8) <= A0;
  s11(9) <= A0;
  s11(10) <= A0;
  s11(11) <= A0;
  s11(12) <= A0;
  s11(13) <= A0;
  s11(14) <= A0;
  s11(15) <= A0;
  s14 <= RA(1);
  s15 <= RA(2);
  s16 <= RA(3);
  s17 <= RA(4);
  s18 <= RA(5);
  s19 <= RA(6);
  s20 <= RA(7);
  s21 <= RA(8);
  s22 <= RA(9);
  s23 <= RA(10);
  s24 <= RA(11);
  s25 <= RA(12);
  s26 <= RA(13);
  s27 <= RA(14);
  s30 <= RB(1);
  s31 <= RB(2);
  s32 <= RB(3);
  s33 <= RB(4);
  s34 <= RB(5);
  s35 <= RB(6);
  s36 <= RB(7);
  s37 <= RB(8);
  s38 <= RB(9);
  s39 <= RB(10);
  s40 <= RB(11);
  s41 <= RB(12);
  s42 <= RB(13);
  s43 <= RB(14);
  gate2: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 16)
    port map (
      sel => s6,
      in_0 => s3,
      in_1 => s4,
      in_2 => s5,
      in_3 => RA,
      p_out => s7);
  s0 <= (s10 XOR s11);
  s28(0) <= '0';
  s28(1) <= RA(0);
  s28(2) <= s14;
  s28(3) <= s15;
  s28(4) <= s16;
  s28(5) <= s17;
  s28(6) <= s18;
  s28(7) <= s19;
  s28(8) <= s20;
  s28(9) <= s21;
  s28(10) <= s22;
  s28(11) <= s23;
  s28(12) <= s24;
  s28(13) <= s25;
  s28(14) <= s26;
  s28(15) <= s27;
  s29(0) <= s14;
  s29(1) <= s15;
  s29(2) <= s16;
  s29(3) <= s17;
  s29(4) <= s18;
  s29(5) <= s19;
  s29(6) <= s20;
  s29(7) <= s21;
  s29(8) <= s22;
  s29(9) <= s23;
  s29(10) <= s24;
  s29(11) <= s25;
  s29(12) <= s26;
  s29(13) <= s27;
  s29(14) <= RA(15);
  s29(15) <= '0';
  s44(0) <= '0';
  s44(1) <= RB(0);
  s44(2) <= s30;
  s44(3) <= s31;
  s44(4) <= s32;
  s44(5) <= s33;
  s44(6) <= s34;
  s44(7) <= s35;
  s44(8) <= s36;
  s44(9) <= s37;
  s44(10) <= s38;
  s44(11) <= s39;
  s44(12) <= s40;
  s44(13) <= s41;
  s44(14) <= s42;
  s44(15) <= s43;
  s45(0) <= s30;
  s45(1) <= s31;
  s45(2) <= s32;
  s45(3) <= s33;
  s45(4) <= s34;
  s45(5) <= s35;
  s45(6) <= s36;
  s45(7) <= s37;
  s45(8) <= s38;
  s45(9) <= s39;
  s45(10) <= s40;
  s45(11) <= s41;
  s45(12) <= s42;
  s45(13) <= s43;
  s45(14) <= RB(15);
  s45(15) <= '0';
  gate3: entity work.DIG_Add
    generic map (
      Bits => 16)
    port map (
      a => RA,
      b => s0,
      c_i => s1,
      s => s2,
      c_o => CARRY_OUT);
  s9 <= (s8 XOR s7);
  gate4: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 16)
    port map (
      sel => s6,
      in_0 => s28,
      in_1 => s29,
      in_2 => s44,
      in_3 => s45,
      p_out => s13);
  gate5: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 16)
    port map (
      sel => s12,
      in_0 => s2,
      in_1 => s13,
      in_2 => s9,
      in_3 => s9,
      p_out => ALU_OUT);
end Behavioral;
