-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_2 is
  port (
    p_out: out std_logic;
    sel: in std_logic_vector (1 downto 0);
    
    in_0: in std_logic;
    in_1: in std_logic;
    in_2: in std_logic;
    in_3: in std_logic );
end MUX_GATE_2;

architecture Behavioral of MUX_GATE_2 is
begin
  with sel select
    p_out <=
      in_0 when "00",
      in_1 when "01",
      in_2 when "10",
      in_3 when "11",
      '0' when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    Z: in std_logic;
    C: in std_logic;
    N: in std_logic;
    V: in std_logic;
    COND_VALUE: in std_logic;
    COND_FLAG: in std_logic_vector(1 downto 0);
    COND_CHECKEROUT: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic;
begin
  gate0: entity work.MUX_GATE_2
    port map (
      sel => COND_FLAG,
      in_0 => Z,
      in_1 => C,
      in_2 => N,
      in_3 => V,
      p_out => s0);
  COND_CHECKEROUT <= NOT (s0 XOR COND_VALUE);
end Behavioral;
