-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_1 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_1;

architecture Behavioral of MUX_GATE_BUS_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_1 is
  port (
    p_out: out std_logic;
    sel: in std_logic;
    
    in_0: in std_logic;
    in_1: in std_logic );
end MUX_GATE_1;

architecture Behavioral of MUX_GATE_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      '0' when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_Register_BUS is
  generic ( Bits: integer ); 
  port (
    Q: out std_logic_vector ((Bits-1) downto 0);
    D: in std_logic_vector ((Bits-1) downto 0);
    C: in std_logic;
    en: in std_logic );
end DIG_Register_BUS;

architecture Behavioral of DIG_Register_BUS is
  signal state : std_logic_vector ((Bits-1) downto 0) := (others => '0');
begin
   Q <= state;

   process ( C )
   begin
      if rising_edge(C) and (en='1') then
        state <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    FLAGS_LOAD: in std_logic;
    ALU_OUT: in std_logic_vector(15 downto 0);
    MEMORY_BUS: in std_logic_vector(15 downto 0);
    DEC_COUNT_OUT: in std_logic_vector(15 downto 0);
    FLAGS_LOAD_SEL1: in std_logic;
    FLAGS_LOAD_SEL0: in std_logic;
    CARRY_OUT: in std_logic;
    ALU_OP: in std_logic_vector(3 downto 0);
    RB: in std_logic_vector(15 downto 0);
    RA: in std_logic_vector(15 downto 0);
    CLK: in std_logic;
    Z: out std_logic;
    C: out std_logic;
    N: out std_logic;
    V: out std_logic);
end main;

architecture Behavioral of main is
  signal s0: std_logic_vector(15 downto 0);
  signal s1: std_logic_vector(3 downto 0);
  signal s2: std_logic;
  signal s3: std_logic_vector(3 downto 0);
  signal s4: std_logic;
  signal s5: std_logic_vector(3 downto 0);
  signal s6: std_logic_vector(3 downto 0);
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
begin
  gate0: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 16)
    port map (
      sel => FLAGS_LOAD_SEL1,
      in_0 => ALU_OUT,
      in_1 => DEC_COUNT_OUT,
      p_out => s0);
  s6(0) <= MEMORY_BUS(0);
  s6(1) <= MEMORY_BUS(1);
  s6(2) <= MEMORY_BUS(2);
  s6(3) <= MEMORY_BUS(3);
  s2 <= (FLAGS_LOAD AND CLK);
  s10 <= ALU_OP(0);
  s8 <= RB(15);
  s7 <= RA(15);
  s4 <= s0(15);
  s9 <= ((NOT s7 AND NOT s8 AND s4) OR (s7 AND s8 AND NOT s4));
  s11 <= ((NOT s7 AND s8 AND s4) OR (s7 AND NOT s8 AND NOT s4));
  gate1: entity work.MUX_GATE_1
    port map (
      sel => s10,
      in_0 => s9,
      in_1 => s11,
      p_out => s12);
  s5(0) <= NOT (s0(0) OR s0(1) OR s0(2) OR s0(3) OR s0(4) OR s0(5) OR s0(6) OR s0(7) OR s0(8) OR s0(9) OR s0(10) OR s0(11) OR s0(12) OR s0(13) OR s0(14) OR s4);
  s5(1) <= CARRY_OUT;
  s5(2) <= s4;
  s5(3) <= (s12 AND NOT (ALU_OP(1) OR ALU_OP(2) OR ALU_OP(3)));
  gate2: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 4)
    port map (
      sel => FLAGS_LOAD_SEL0,
      in_0 => s5,
      in_1 => s6,
      p_out => s1);
  gate3: entity work.DIG_Register_BUS -- FLAGS
    generic map (
      Bits => 4)
    port map (
      D => s1,
      C => s2,
      en => '1',
      Q => s3);
  Z <= s3(0);
  C <= s3(1);
  N <= s3(2);
  V <= s3(3);
end Behavioral;
