-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_Register_BUS is
  generic ( Bits: integer ); 
  port (
    Q: out std_logic_vector ((Bits-1) downto 0);
    D: in std_logic_vector ((Bits-1) downto 0);
    C: in std_logic;
    en: in std_logic );
end DIG_Register_BUS;

architecture Behavioral of DIG_Register_BUS is
  signal state : std_logic_vector ((Bits-1) downto 0) := (others => '0');
begin
   Q <= state;

   process ( C )
   begin
      if rising_edge(C) and (en='1') then
        state <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    PROG_ROM: in std_logic_vector(15 downto 0);
    CLK: in std_logic;
    IR_LOAD: in std_logic;
    IMM_LOAD: in std_logic;
    REG_B: out std_logic_vector(2 downto 0);
    REG_A: out std_logic_vector(2 downto 0);
    OPCODE: out std_logic_vector(5 downto 0);
    WB: out std_logic_vector(15 downto 0);
    MAR: out std_logic_vector(15 downto 0);
    DEC_COUNTER: out std_logic_vector(15 downto 0));
end main;

architecture Behavioral of main is
  signal s0: std_logic_vector(15 downto 0);
  signal DEC_COUNTER_temp: std_logic_vector(15 downto 0);
begin
  gate0: entity work.DIG_Register_BUS -- IR
    generic map (
      Bits => 16)
    port map (
      D => PROG_ROM,
      C => CLK,
      en => IR_LOAD,
      Q => s0);
  gate1: entity work.DIG_Register_BUS -- IMM
    generic map (
      Bits => 16)
    port map (
      D => PROG_ROM,
      C => CLK,
      en => IMM_LOAD,
      Q => DEC_COUNTER_temp);
  REG_B <= s0(6 downto 4);
  REG_A <= s0(9 downto 7);
  OPCODE <= s0(15 downto 10);
  WB <= DEC_COUNTER_temp;
  MAR <= DEC_COUNTER_temp;
  DEC_COUNTER <= DEC_COUNTER_temp;
end Behavioral;
