-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_2 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic_vector (1 downto 0);
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0);
    in_2: in std_logic_vector ((Bits-1) downto 0);
    in_3: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_2;

architecture Behavioral of MUX_GATE_BUS_2 is
begin
  with sel select
    p_out <=
      in_0 when "00",
      in_1 when "01",
      in_2 when "10",
      in_3 when "11",
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_Register_BUS is
  generic ( Bits: integer ); 
  port (
    Q: out std_logic_vector ((Bits-1) downto 0);
    D: in std_logic_vector ((Bits-1) downto 0);
    C: in std_logic;
    en: in std_logic );
end DIG_Register_BUS;

architecture Behavioral of DIG_Register_BUS is
  signal state : std_logic_vector ((Bits-1) downto 0) := (others => '0');
begin
   Q <= state;

   process ( C )
   begin
      if rising_edge(C) and (en='1') then
        state <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DECODER_1 is
  port (
    out_0: out std_logic;
    out_1: out std_logic;
    sel: in std_logic );
end DECODER_1;

architecture Behavioral of DECODER_1 is
begin
  out_0 <= '1' when sel = '0' else '0';
  out_1 <= '1' when sel = '1' else '0';
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DECODER_2 is
  port (
    out_0: out std_logic;
    out_1: out std_logic;
    out_2: out std_logic;
    out_3: out std_logic;
    sel: in std_logic_vector (1 downto 0) );
end DECODER_2;

architecture Behavioral of DECODER_2 is
begin
  out_0 <= '1' when sel = "00" else '0';
  out_1 <= '1' when sel = "01" else '0';
  out_2 <= '1' when sel = "10" else '0';
  out_3 <= '1' when sel = "11" else '0';
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
use IEEE.NUMERIC_STD.ALL;

entity DIG_ROM_DATA_ROM is
  port (
    D: out std_logic_vector (15 downto 0);
    A: in std_logic_vector (13 downto 0);
    sel: in std_logic );
end DIG_ROM_DATA_ROM;

architecture Behavioral of DIG_ROM_DATA_ROM is
  type mem is array ( 0 to -1) of std_logic_vector (15 downto 0);
  constant my_Rom : mem := (
    );
begin
  process (A, sel)
  begin
    if sel='0' then
      D <= (others => 'Z');
    elsif A > "11111111111111" then
      D <= (others => '0');
    else
      D <= my_rom(to_integer(unsigned(A)));
    end if;
  end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity PRIORITY_GATE_2 is
  port (
    num: out std_logic_vector (1 downto 0);
    any: out std_logic;
    in0: in std_logic;
    in1: in std_logic;
    in2: in std_logic;
    in3: in std_logic );
end PRIORITY_GATE_2;

architecture Behavioral of PRIORITY_GATE_2 is
begin
  num <=
    "11" when in3 = '1' else
    "10" when in2 = '1' else
    "01" when in1 = '1' else
    "00" ;
  any <= in0 OR in1 OR in2 OR in3;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity DIG_RAMDualPort is
  generic (
    Bits : integer;       
    AddrBits : integer ); 
  port (
    D: out std_logic_vector ((Bits-1) downto 0);
    A: in std_logic_vector ((AddrBits-1) downto 0);
    Din: in std_logic_vector ((Bits-1) downto 0);
    str: in std_logic;
    C: in std_logic;
    ld: in std_logic );
end DIG_RAMDualPort;

architecture Behavioral of DIG_RAMDualPort is
    -- CAUTION: uses distributed RAM
    type memoryType is array(0 to (2**AddrBits)-1) of STD_LOGIC_VECTOR((Bits-1) downto 0);
    signal memory : memoryType;
begin
  process ( C )
  begin
    if rising_edge(C) AND (str='1') then
      memory(to_integer(unsigned(A))) <= Din;
    end if;
  end process;
  D <= memory(to_integer(unsigned(A))) when ld='1' else (others => 'Z');
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_1 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_1;

architecture Behavioral of MUX_GATE_BUS_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DRIVER_INV_GATE_BUS is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    p_in: in std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic );
end DRIVER_INV_GATE_BUS;

architecture Behavioral of DRIVER_INV_GATE_BUS is
begin
  p_out <= p_in when sel = '0' else (others => 'Z');
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    CPU_CLK: in std_logic;
    MEM_WRITE: in std_logic;
    MEM_READ: in std_logic;
    MAR_LOAD: in std_logic;
    MDR_LOAD: in std_logic;
    IMM_OUT: in std_logic_vector(15 downto 0);
    ALU_OUT: in std_logic_vector(15 downto 0);
    RA: in std_logic_vector(15 downto 0);
    RB: in std_logic_vector(15 downto 0);
    MAR_SEL: in std_logic_vector(1 downto 0);
    Z: in std_logic;
    C: in std_logic;
    N: in std_logic;
    V: in std_logic;
    MEM_DATA_SEL: in std_logic_vector(1 downto 0);
    MEM_OUT_BUS: out std_logic_vector(15 downto 0);
    port1: out std_logic_vector(15 downto 0);
    port2: out std_logic_vector(15 downto 0);
    port3: out std_logic_vector(15 downto 0);
    port4: out std_logic_vector(15 downto 0));
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic_vector(15 downto 0);
  signal s4: std_logic_vector(15 downto 0);
  signal MEM_OUT_BUS_temp: std_logic_vector(15 downto 0);
  signal s5: std_logic_vector(15 downto 0);
  signal s6: std_logic_vector(13 downto 0);
  signal s7: std_logic;
  signal s8: std_logic_vector(15 downto 0);
  signal s9: std_logic_vector(14 downto 0);
  signal s10: std_logic_vector(15 downto 0);
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic_vector(15 downto 0);
  signal s14: std_logic;
  signal s15: std_logic_vector(15 downto 0);
  signal s16: std_logic;
  signal s17: std_logic_vector(15 downto 0);
  signal s18: std_logic;
  signal s19: std_logic_vector(15 downto 0);
  signal s20: std_logic;
  signal s21: std_logic_vector(15 downto 0);
  signal s22: std_logic;
  signal s23: std_logic;
  signal s24: std_logic;
  signal s25: std_logic;
  signal s26: std_logic_vector(1 downto 0);
  signal s27: std_logic;
  signal s28: std_logic;
  signal s29: std_logic;
  signal port4_temp: std_logic_vector(15 downto 0);
  signal port3_temp: std_logic_vector(15 downto 0);
  signal port2_temp: std_logic_vector(15 downto 0);
  signal port1_temp: std_logic_vector(15 downto 0);
  signal s30: std_logic_vector(15 downto 0);
  signal s31: std_logic;
  signal s32: std_logic_vector(15 downto 0);
  signal s33: std_logic_vector(15 downto 0);
  signal s34: std_logic_vector(1 downto 0);
begin
  gate0: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 16)
    port map (
      sel => MAR_SEL,
      in_0 => IMM_OUT,
      in_1 => ALU_OUT,
      in_2 => RA,
      in_3 => RB,
      p_out => s3);
  s33(0) <= Z;
  s33(1) <= C;
  s33(2) <= N;
  s33(3) <= V;
  s33(15 downto 4) <= "000000000000";
  gate1: entity work.DIG_Register_BUS -- MAR
    generic map (
      Bits => 16)
    port map (
      D => s3,
      C => CPU_CLK,
      en => MAR_LOAD,
      Q => s4);
  s9 <= s4(14 downto 0);
  s0 <= s4(15);
  s6 <= s4(13 downto 0);
  s22 <= s4(14);
  s26 <= s4(1 downto 0);
  gate2: entity work.DECODER_1
    port map (
      sel => s0,
      out_0 => s1,
      out_1 => s2);
  gate3: entity work.DECODER_1
    port map (
      sel => s22,
      out_0 => s23,
      out_1 => s24);
  gate4: entity work.DECODER_2
    port map (
      sel => s26,
      out_0 => s25,
      out_1 => s27,
      out_2 => s28,
      out_3 => s29);
  s14 <= (s23 AND s25 AND MEM_WRITE);
  s11 <= (MEM_WRITE AND s2);
  s12 <= (MEM_READ AND s2);
  s7 <= (MEM_READ AND (s1 AND s24));
  s16 <= (s23 AND s27 AND MEM_WRITE);
  s18 <= (s23 AND s28 AND MEM_WRITE);
  s20 <= (s23 AND s29 AND MEM_WRITE);
  s31 <= (MEM_READ AND s23);
  gate5: entity work.DIG_ROM_DATA_ROM -- DATA_ROM
    port map (
      A => s6,
      sel => s7,
      D => s8);
  gate6: entity work.PRIORITY_GATE_2
    port map (
      in0 => '0',
      in1 => s12,
      in2 => s7,
      in3 => s31,
      num => s34);
  gate7: entity work.DIG_Register_BUS -- MDR
    generic map (
      Bits => 16)
    port map (
      D => MEM_OUT_BUS_temp,
      C => CPU_CLK,
      en => MDR_LOAD,
      Q => s5);
  gate8: entity work.DIG_RAMDualPort -- RAM
    generic map (
      Bits => 16,
      AddrBits => 15)
    port map (
      A => s9,
      Din => s10,
      str => s11,
      C => CPU_CLK,
      ld => s12,
      D => s13);
  gate9: entity work.DIG_Register_BUS -- GPIO_PORT1
    generic map (
      Bits => 16)
    port map (
      D => s10,
      C => CPU_CLK,
      en => s14,
      Q => s15);
  gate10: entity work.DIG_Register_BUS -- GPIO_PORT2
    generic map (
      Bits => 16)
    port map (
      D => s10,
      C => CPU_CLK,
      en => s16,
      Q => s17);
  gate11: entity work.DIG_Register_BUS -- GPIO_PORT3
    generic map (
      Bits => 16)
    port map (
      D => s10,
      C => CPU_CLK,
      en => s18,
      Q => s19);
  gate12: entity work.DIG_Register_BUS -- GPIO_PORT4
    generic map (
      Bits => 16)
    port map (
      D => s10,
      C => CPU_CLK,
      en => s20,
      Q => s21);
  gate13: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 16)
    port map (
      sel => s26,
      in_0 => port4_temp,
      in_1 => port3_temp,
      in_2 => port2_temp,
      in_3 => port1_temp,
      p_out => s30);
  gate14: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 16)
    port map (
      sel => s31,
      in_0 => "0000000000000000",
      in_1 => s30,
      p_out => s32);
  gate15: entity work.DRIVER_INV_GATE_BUS
    generic map (
      Bits => 16)
    port map (
      p_in => s17,
      sel => MEM_READ,
      p_out => port3_temp);
  gate16: entity work.DRIVER_INV_GATE_BUS
    generic map (
      Bits => 16)
    port map (
      p_in => s19,
      sel => MEM_READ,
      p_out => port2_temp);
  gate17: entity work.DRIVER_INV_GATE_BUS
    generic map (
      Bits => 16)
    port map (
      p_in => s15,
      sel => MEM_READ,
      p_out => port4_temp);
  gate18: entity work.DRIVER_INV_GATE_BUS
    generic map (
      Bits => 16)
    port map (
      p_in => s21,
      sel => MEM_READ,
      p_out => port1_temp);
  gate19: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 16)
    port map (
      sel => MEM_DATA_SEL,
      in_0 => RA,
      in_1 => RB,
      in_2 => s33,
      in_3 => s5,
      p_out => s10);
  gate20: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 16)
    port map (
      sel => s34,
      in_0 => "0000000000000000",
      in_1 => s13,
      in_2 => s8,
      in_3 => s32,
      p_out => MEM_OUT_BUS_temp);
  MEM_OUT_BUS <= MEM_OUT_BUS_temp;
  port1 <= port1_temp;
  port2 <= port2_temp;
  port3 <= port3_temp;
  port4 <= port4_temp;
end Behavioral;
