-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
use IEEE.NUMERIC_STD.ALL;

entity DIG_ROM_INSTRUCTION_ROM is
  port (
    D: out std_logic_vector (15 downto 0);
    A: in std_logic_vector (15 downto 0);
    sel: in std_logic );
end DIG_ROM_INSTRUCTION_ROM;

architecture Behavioral of DIG_ROM_INSTRUCTION_ROM is
  type mem is array ( 0 to 18) of std_logic_vector (15 downto 0);
  constant my_Rom : mem := (
    "0111000010001000", "0000011100000000", "0000000010001111", 
    "0000010000000000", "0000000000100100", "0111000011101100", 
    "0000000100000000", "0000000011110111", "0000001000000000", 
    "1111000010001000", "0000010100000000", "0001000010001111", 
    "0000001000000000", "1001000000100100", "1111000011101100", 
    "0000001100000000", "0001000011110111", "0000010000000000", 
    "0111000011111111");
begin
  process (A, sel)
  begin
    if sel='0' then
      D <= (others => 'Z');
    elsif A > "0000000000010010" then
      D <= (others => '0');
    else
      D <= my_rom(to_integer(unsigned(A)));
    end if;
  end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    PC_OUT: in std_logic_vector(15 downto 0);
    PROG_ROM: out std_logic_vector(15 downto 0));
end main;

architecture Behavioral of main is
begin
  gate0: entity work.DIG_ROM_INSTRUCTION_ROM -- INSTRUCTION_ROM
    port map (
      A => PC_OUT,
      sel => '1',
      D => PROG_ROM);
end Behavioral;
