-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;
use ieee.numeric_std.all;

entity DIG_CounterPreset is
  generic ( Bits: integer;
            maxValue: integer );
  port (
    p_out : out std_logic_vector((Bits-1) downto 0);
    ovf : out std_logic;
    C   : in std_logic;
    en  : in std_logic;
    clr : in std_logic;
    dir : in std_logic;
    p_in  : in std_logic_vector((Bits-1) downto 0);
    ld  : in std_logic );
end DIG_CounterPreset;

architecture Behavioral of DIG_CounterPreset is
   signal count : std_logic_vector((Bits-1) downto 0) := (others => '0');

   function maxVal ( maxv : integer )
       return integer is variable m : integer;
   begin
      if (maxv = 0) then
        m := (2**Bits)-1;
      else
        m := maxv;
      end if;
      return m;
   end function maxVal;

begin
    process (C, en)
    begin
      if rising_edge(C) then
        if clr='1' then
          count <= (others => '0');
        elsif ld='1' then
          count <= p_in;
        elsif en='1' then
          if dir='0' then
            if count=maxVal(maxValue) then
              count <= (others => '0');
            else
              count <= count + 1;
            end if;
          else
            if count=0 then
              count <= std_logic_vector(to_unsigned(maxVal(maxValue), Bits));
            else
              count <= count - 1;
            end if;
          end if;
        end if;
      end if;
    end process;

    p_out <= count;
    ovf <= en when (count = maxVal(maxValue) and dir='0') OR
                   (count = 0 and dir='1') else '0';
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    CPU_CLK: in std_logic;
    PC_EN: in std_logic;
    ALU_OUT: in std_logic_vector(15 downto 0);
    PC_SEL: in std_logic;
    PC_OUT: out std_logic_vector(15 downto 0));
end main;

architecture Behavioral of main is
begin
  gate0: entity work.DIG_CounterPreset -- PC
    generic map (
      Bits => 16,
      maxValue => 0)
    port map (
      en => PC_EN,
      C => CPU_CLK,
      dir => '0',
      p_in => ALU_OUT,
      ld => PC_SEL,
      clr => '0',
      p_out => PC_OUT);
end Behavioral;
