-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity DEMUX_GATE_3 is
  generic (
    Default : integer );
  port (
    out_0: out std_logic;
    out_1: out std_logic;
    out_2: out std_logic;
    out_3: out std_logic;
    out_4: out std_logic;
    out_5: out std_logic;
    out_6: out std_logic;
    out_7: out std_logic;
    sel: in std_logic_vector (2 downto 0);
    p_in: in std_logic );
end DEMUX_GATE_3;

architecture Behavioral of DEMUX_GATE_3 is
begin
    out_0 <= p_in when sel = "000" else std_logic(to_unsigned(Default, 1)(0));
    out_1 <= p_in when sel = "001" else std_logic(to_unsigned(Default, 1)(0));
    out_2 <= p_in when sel = "010" else std_logic(to_unsigned(Default, 1)(0));
    out_3 <= p_in when sel = "011" else std_logic(to_unsigned(Default, 1)(0));
    out_4 <= p_in when sel = "100" else std_logic(to_unsigned(Default, 1)(0));
    out_5 <= p_in when sel = "101" else std_logic(to_unsigned(Default, 1)(0));
    out_6 <= p_in when sel = "110" else std_logic(to_unsigned(Default, 1)(0));
    out_7 <= p_in when sel = "111" else std_logic(to_unsigned(Default, 1)(0));
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_Register_BUS is
  generic ( Bits: integer ); 
  port (
    Q: out std_logic_vector ((Bits-1) downto 0);
    D: in std_logic_vector ((Bits-1) downto 0);
    C: in std_logic;
    en: in std_logic );
end DIG_Register_BUS;

architecture Behavioral of DIG_Register_BUS is
  signal state : std_logic_vector ((Bits-1) downto 0) := (others => '0');
begin
   Q <= state;

   process ( C )
   begin
      if rising_edge(C) and (en='1') then
        state <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_3 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic_vector (2 downto 0);
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0);
    in_2: in std_logic_vector ((Bits-1) downto 0);
    in_3: in std_logic_vector ((Bits-1) downto 0);
    in_4: in std_logic_vector ((Bits-1) downto 0);
    in_5: in std_logic_vector ((Bits-1) downto 0);
    in_6: in std_logic_vector ((Bits-1) downto 0);
    in_7: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_3;

architecture Behavioral of MUX_GATE_BUS_3 is
begin
  with sel select
    p_out <=
      in_0 when "000",
      in_1 when "001",
      in_2 when "010",
      in_3 when "011",
      in_4 when "100",
      in_5 when "101",
      in_6 when "110",
      in_7 when "111",
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    REG_A: in std_logic_vector(2 downto 0);
    CLK: in std_logic;
    REG_B: in std_logic_vector(2 downto 0);
    A_RW: in std_logic;
    B_RW: in std_logic;
    DATA_IN: in std_logic_vector(15 downto 0);
    RA: out std_logic_vector(15 downto 0);
    RB: out std_logic_vector(15 downto 0));
end main;

architecture Behavioral of main is
  signal s0: std_logic;
  signal s1: std_logic_vector(15 downto 0);
  signal s2: std_logic;
  signal s3: std_logic_vector(15 downto 0);
  signal s4: std_logic;
  signal s5: std_logic_vector(15 downto 0);
  signal s6: std_logic;
  signal s7: std_logic_vector(15 downto 0);
  signal s8: std_logic;
  signal s9: std_logic_vector(15 downto 0);
  signal s10: std_logic;
  signal s11: std_logic_vector(15 downto 0);
  signal s12: std_logic;
  signal s13: std_logic_vector(15 downto 0);
  signal s14: std_logic;
  signal s15: std_logic_vector(15 downto 0);
  signal s16: std_logic;
  signal s17: std_logic_vector(15 downto 0);
  signal s18: std_logic;
  signal s19: std_logic_vector(15 downto 0);
  signal s20: std_logic;
  signal s21: std_logic_vector(15 downto 0);
  signal s22: std_logic;
  signal s23: std_logic_vector(15 downto 0);
  signal s24: std_logic;
  signal s25: std_logic_vector(15 downto 0);
  signal s26: std_logic;
  signal s27: std_logic_vector(15 downto 0);
  signal s28: std_logic;
  signal s29: std_logic_vector(15 downto 0);
  signal s30: std_logic;
  signal s31: std_logic_vector(15 downto 0);
begin
  gate0: entity work.DEMUX_GATE_3
    generic map (
      Default => 0)
    port map (
      sel => REG_A,
      p_in => A_RW,
      out_0 => s0,
      out_1 => s2,
      out_2 => s4,
      out_3 => s6,
      out_4 => s8,
      out_5 => s10,
      out_6 => s12,
      out_7 => s14);
  gate1: entity work.DEMUX_GATE_3
    generic map (
      Default => 0)
    port map (
      sel => REG_B,
      p_in => B_RW,
      out_0 => s16,
      out_1 => s18,
      out_2 => s20,
      out_3 => s22,
      out_4 => s24,
      out_5 => s26,
      out_6 => s28,
      out_7 => s30);
  gate2: entity work.DIG_Register_BUS -- A0
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s0,
      Q => s1);
  gate3: entity work.DIG_Register_BUS -- A1
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s2,
      Q => s3);
  gate4: entity work.DIG_Register_BUS -- A2
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s4,
      Q => s5);
  gate5: entity work.DIG_Register_BUS -- A3
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s6,
      Q => s7);
  gate6: entity work.DIG_Register_BUS -- A4
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s8,
      Q => s9);
  gate7: entity work.DIG_Register_BUS -- A5
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s10,
      Q => s11);
  gate8: entity work.DIG_Register_BUS -- A6
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s12,
      Q => s13);
  gate9: entity work.DIG_Register_BUS -- A7
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s14,
      Q => s15);
  gate10: entity work.DIG_Register_BUS -- B0
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s16,
      Q => s17);
  gate11: entity work.DIG_Register_BUS -- B1
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s18,
      Q => s19);
  gate12: entity work.DIG_Register_BUS -- B2
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s20,
      Q => s21);
  gate13: entity work.DIG_Register_BUS -- B3
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s22,
      Q => s23);
  gate14: entity work.DIG_Register_BUS -- B4
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s24,
      Q => s25);
  gate15: entity work.DIG_Register_BUS -- B5
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s26,
      Q => s27);
  gate16: entity work.DIG_Register_BUS -- B6
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s28,
      Q => s29);
  gate17: entity work.DIG_Register_BUS -- B7
    generic map (
      Bits => 16)
    port map (
      D => DATA_IN,
      C => CLK,
      en => s30,
      Q => s31);
  gate18: entity work.MUX_GATE_BUS_3
    generic map (
      Bits => 16)
    port map (
      sel => REG_A,
      in_0 => s1,
      in_1 => s3,
      in_2 => s5,
      in_3 => s7,
      in_4 => s9,
      in_5 => s11,
      in_6 => s13,
      in_7 => s15,
      p_out => RA);
  gate19: entity work.MUX_GATE_BUS_3
    generic map (
      Bits => 16)
    port map (
      sel => REG_B,
      in_0 => s17,
      in_1 => s19,
      in_2 => s21,
      in_3 => s23,
      in_4 => s25,
      in_5 => s27,
      in_6 => s29,
      in_7 => s31,
      p_out => RB);
end Behavioral;
