-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;

entity DIG_Add is
  generic ( Bits: integer ); 
  port (
    s: out std_logic_vector((Bits-1) downto 0);
    c_o: out std_logic;
    a: in std_logic_vector((Bits-1) downto 0);
    b: in std_logic_vector((Bits-1) downto 0);
    c_i: in std_logic );
end DIG_Add;

architecture Behavioral of DIG_Add is
   signal temp : std_logic_vector(Bits downto 0);
begin
   temp <= ('0' & a) + b + c_i;

   s    <= temp((Bits-1) downto 0);
   c_o  <= temp(Bits);
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_1 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_1;

architecture Behavioral of MUX_GATE_BUS_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_Register_BUS is
  generic ( Bits: integer ); 
  port (
    Q: out std_logic_vector ((Bits-1) downto 0);
    D: in std_logic_vector ((Bits-1) downto 0);
    C: in std_logic;
    en: in std_logic );
end DIG_Register_BUS;

architecture Behavioral of DIG_Register_BUS is
  signal state : std_logic_vector ((Bits-1) downto 0) := (others => '0');
begin
   Q <= state;

   process ( C )
   begin
      if rising_edge(C) and (en='1') then
        state <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    N: in std_logic;
    OPCODE: in std_logic_vector(5 downto 0);
    uSTEP_RESET: in std_logic;
    uSTEP: in std_logic_vector(5 downto 0);
    CLK: in std_logic;
    DIV_CTRL: out std_logic;
    DIV_RESULT: out std_logic_vector(15 downto 0));
end main;

architecture Behavioral of main is
  signal s0: std_logic_vector(15 downto 0);
  signal DIV_RESULT_temp: std_logic_vector(15 downto 0);
  signal s1: std_logic_vector(15 downto 0);
  signal s2: std_logic_vector(15 downto 0);
begin
  DIV_CTRL <= (N AND (OPCODE(0) AND NOT OPCODE(1) AND NOT OPCODE(2) AND OPCODE(3) AND NOT OPCODE(4) AND NOT OPCODE(5)));
  s0(0) <= (NOT uSTEP(0) AND NOT uSTEP(1) AND uSTEP(2) AND NOT uSTEP(3) AND NOT uSTEP(4) AND NOT uSTEP(5));
  s0(15 downto 1) <= "000000000000000";
  gate0: entity work.DIG_Add
    generic map (
      Bits => 16)
    port map (
      a => s0,
      b => DIV_RESULT_temp,
      c_i => '0',
      s => s1);
  gate1: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 16)
    port map (
      sel => uSTEP_RESET,
      in_0 => s1,
      in_1 => "0000000000000000",
      p_out => s2);
  gate2: entity work.DIG_Register_BUS -- DIV_RESULT
    generic map (
      Bits => 16)
    port map (
      D => s2,
      C => CLK,
      en => '1',
      Q => DIV_RESULT_temp);
  DIV_RESULT <= DIV_RESULT_temp;
end Behavioral;
