-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_1 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_1;

architecture Behavioral of MUX_GATE_BUS_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_2 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic_vector (1 downto 0);
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0);
    in_2: in std_logic_vector ((Bits-1) downto 0);
    in_3: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_2;

architecture Behavioral of MUX_GATE_BUS_2 is
begin
  with sel select
    p_out <=
      in_0 when "00",
      in_1 when "01",
      in_2 when "10",
      in_3 when "11",
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    MEM_OUTBUS: in std_logic_vector(15 downto 0);
    ALU_OUT: in std_logic_vector(15 downto 0);
    DIV_RESULT: in std_logic_vector(15 downto 0);
    MUL_RESULT: in std_logic_vector(15 downto 0);
    IMM_OUT: in std_logic_vector(15 downto 0);
    PC_OUT: in std_logic_vector(15 downto 0);
    DIV_CTRL: in std_logic;
    MUL_CTRL: in std_logic;
    WB_SEL: in std_logic_vector(1 downto 0);
    DATA_IN: out std_logic_vector(15 downto 0));
end main;

architecture Behavioral of main is
  signal s0: std_logic_vector(15 downto 0);
  signal s1: std_logic_vector(15 downto 0);
begin
  gate0: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 16)
    port map (
      sel => DIV_CTRL,
      in_0 => ALU_OUT,
      in_1 => DIV_RESULT,
      p_out => s0);
  gate1: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 16)
    port map (
      sel => MUL_CTRL,
      in_0 => s0,
      in_1 => MUL_RESULT,
      p_out => s1);
  gate2: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 16)
    port map (
      sel => WB_SEL,
      in_0 => MEM_OUTBUS,
      in_1 => s1,
      in_2 => IMM_OUT,
      in_3 => PC_OUT,
      p_out => DATA_IN);
end Behavioral;
