/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_4x1
(
    input [1:0] sel,
    input in_0,
    input in_1,
    input in_2,
    input in_3,
    output reg out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module COND_CHECKER (
  input Z,
  input C,
  input N,
  input V,
  input COND_VALUE,
  input [1:0] COND_FLAG,
  output COND_CHECKEROUT
);
  wire s0;
  Mux_4x1 Mux_4x1_i0 (
    .sel( COND_FLAG ),
    .in_0( Z ),
    .in_1( C ),
    .in_2( N ),
    .in_3( V ),
    .out( s0 )
  );
  assign COND_CHECKEROUT = ~ (s0 ^ COND_VALUE);
endmodule
