/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module FLAGS (
  input FLAGS_LOAD,
  input [15:0] ALU_OUT,
  input [15:0] MEMORY_BUS,
  input [15:0] DEC_COUNT_OUT,
  input FLAGS_LOAD_SEL1,
  input FLAGS_LOAD_SEL0,
  input CARRY_OUT,
  input [3:0] ALU_OP,
  input [15:0] RB,
  input [15:0] RA,
  input CLK,
  output Z,
  output C,
  output N,
  output V
);
  wire [15:0] s0;
  wire [3:0] s1;
  wire s2;
  wire [3:0] s3;
  wire s4;
  wire [3:0] s5;
  wire [3:0] s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i0 (
    .sel( FLAGS_LOAD_SEL1 ),
    .in_0( ALU_OUT ),
    .in_1( DEC_COUNT_OUT ),
    .out( s0 )
  );
  assign s6[0] = MEMORY_BUS[0];
  assign s6[1] = MEMORY_BUS[1];
  assign s6[2] = MEMORY_BUS[2];
  assign s6[3] = MEMORY_BUS[3];
  assign s2 = (FLAGS_LOAD & CLK);
  assign s10 = ALU_OP[0];
  assign s8 = RB[15];
  assign s7 = RA[15];
  assign s4 = s0[15];
  assign s9 = ((~ s7 & ~ s8 & s4) | (s7 & s8 & ~ s4));
  assign s11 = ((~ s7 & s8 & s4) | (s7 & ~ s8 & ~ s4));
  Mux_2x1 Mux_2x1_i1 (
    .sel( s10 ),
    .in_0( s9 ),
    .in_1( s11 ),
    .out( s12 )
  );
  assign s5[0] = ~ (s0[0] | s0[1] | s0[2] | s0[3] | s0[4] | s0[5] | s0[6] | s0[7] | s0[8] | s0[9] | s0[10] | s0[11] | s0[12] | s0[13] | s0[14] | s4);
  assign s5[1] = CARRY_OUT;
  assign s5[2] = s4;
  assign s5[3] = (s12 & ~ (ALU_OP[1] | ALU_OP[2] | ALU_OP[3]));
  Mux_2x1_NBits #(
    .Bits(4)
  )
  Mux_2x1_NBits_i2 (
    .sel( FLAGS_LOAD_SEL0 ),
    .in_0( s5 ),
    .in_1( s6 ),
    .out( s1 )
  );
  // FLAGS
  DIG_Register_BUS #(
    .Bits(4)
  )
  DIG_Register_BUS_i3 (
    .D( s1 ),
    .C( s2 ),
    .en( 1'b1 ),
    .Q( s3 )
  );
  assign Z = s3[0];
  assign C = s3[1];
  assign N = s3[2];
  assign V = s3[3];
endmodule
