/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module IR_and_IMM (
  input [15:0] PROG_ROM,
  input CLK,
  input IR_LOAD,
  input IMM_LOAD,
  output [2:0] REG_B,
  output [2:0] REG_A,
  output [5:0] OPCODE,
  output [15:0] WB,
  output [15:0] MAR,
  output [15:0] DEC_COUNTER
);
  wire [15:0] s0;
  wire [15:0] DEC_COUNTER_temp;
  // IR
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i0 (
    .D( PROG_ROM ),
    .C( CLK ),
    .en( IR_LOAD ),
    .Q( s0 )
  );
  // IMM
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i1 (
    .D( PROG_ROM ),
    .C( CLK ),
    .en( IMM_LOAD ),
    .Q( DEC_COUNTER_temp )
  );
  assign REG_B = s0[6:4];
  assign REG_A = s0[9:7];
  assign OPCODE = s0[15:10];
  assign WB = DEC_COUNTER_temp;
  assign MAR = DEC_COUNTER_temp;
  assign DEC_COUNTER = DEC_COUNTER_temp;
endmodule
