/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Decoder1 (
    output out_0,
    output out_1,
    input [0:0] sel
);
    assign out_0 = (sel == 1'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 1'h1)? 1'b1 : 1'b0;
endmodule


module Decoder2 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    input [1:0] sel
);
    assign out_0 = (sel == 2'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 2'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 2'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 2'h3)? 1'b1 : 1'b0;
endmodule

module DIG_ROM_16384X16_DATA_ROM (
    input [13:0] A,
    input sel,
    output reg [15:0] D
);
    reg [15:0] my_rom [0:-1];

    always @ (*) begin
        if (~sel)
            D = 16'hz;
        else if (A > 14'hffffffffffffffff)
            D = 16'h0;
        else
            D = my_rom[A];
    end

    initial begin
    end
endmodule

module PriorityEncoder2 (
    input in0,
    input in1,
    input in2,
    input in3,
    output reg [1:0] num,
    output any
);
    always @ (*) begin
        if (in3 == 1'b1)
            num = 2'h3;
        else if (in2 == 1'b1)
            num = 2'h2;
        else if (in1 == 1'b1)
            num = 2'h1;
        else 
            num = 2'h0;
    end

    assign any = in0 | in1 | in2 | in3;
endmodule

module DIG_RAMDualPort
#(
    parameter Bits = 8,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  input ld,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];

  assign D = ld? memory[A] : 'hz;

  always @ (posedge C) begin
    if (str)
      memory[A] <= Din;
  end
endmodule


module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DriverInvBus#(
    parameter Bits = 2
)
(
    input [(Bits-1):0] in,
    input sel,
    output [(Bits-1):0] out
);
    assign out = (sel == 1'b0)? in : {Bits{1'bz}};
endmodule

module MEMORY (
  input CPU_CLK,
  input MEM_WRITE,
  input MEM_READ,
  input MAR_LOAD,
  input MDR_LOAD,
  input [15:0] IMM_OUT,
  input [15:0] ALU_OUT,
  input [15:0] RA,
  input [15:0] RB,
  input [1:0] MAR_SEL,
  input Z,
  input C,
  input N,
  input V,
  input [1:0] MEM_DATA_SEL,
  output [15:0] MEM_OUT_BUS,
  output [15:0] port1,
  output [15:0] port2,
  output [15:0] port3,
  output [15:0] port4
);
  wire s0;
  wire s1;
  wire s2;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] MEM_OUT_BUS_temp;
  wire [15:0] s5;
  wire [13:0] s6;
  wire s7;
  wire [15:0] s8;
  wire [14:0] s9;
  wire [15:0] s10;
  wire s11;
  wire s12;
  wire [15:0] s13;
  wire s14;
  wire [15:0] s15;
  wire s16;
  wire [15:0] s17;
  wire s18;
  wire [15:0] s19;
  wire s20;
  wire [15:0] s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire [1:0] s26;
  wire s27;
  wire s28;
  wire s29;
  wire [15:0] port4_temp;
  wire [15:0] port3_temp;
  wire [15:0] port2_temp;
  wire [15:0] port1_temp;
  wire [15:0] s30;
  wire s31;
  wire [15:0] s32;
  wire [15:0] s33;
  wire [1:0] s34;
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i0 (
    .sel( MAR_SEL ),
    .in_0( IMM_OUT ),
    .in_1( ALU_OUT ),
    .in_2( RA ),
    .in_3( RB ),
    .out( s3 )
  );
  assign s33[0] = Z;
  assign s33[1] = C;
  assign s33[2] = N;
  assign s33[3] = V;
  assign s33[15:4] = 12'b0;
  // MAR
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i1 (
    .D( s3 ),
    .C( CPU_CLK ),
    .en( MAR_LOAD ),
    .Q( s4 )
  );
  assign s9 = s4[14:0];
  assign s0 = s4[15];
  assign s6 = s4[13:0];
  assign s22 = s4[14];
  assign s26 = s4[1:0];
  Decoder1 Decoder1_i2 (
    .sel( s0 ),
    .out_0( s1 ),
    .out_1( s2 )
  );
  Decoder1 Decoder1_i3 (
    .sel( s22 ),
    .out_0( s23 ),
    .out_1( s24 )
  );
  Decoder2 Decoder2_i4 (
    .sel( s26 ),
    .out_0( s25 ),
    .out_1( s27 ),
    .out_2( s28 ),
    .out_3( s29 )
  );
  assign s14 = (s23 & s25 & MEM_WRITE);
  assign s11 = (MEM_WRITE & s2);
  assign s12 = (MEM_READ & s2);
  assign s7 = (MEM_READ & (s1 & s24));
  assign s16 = (s23 & s27 & MEM_WRITE);
  assign s18 = (s23 & s28 & MEM_WRITE);
  assign s20 = (s23 & s29 & MEM_WRITE);
  assign s31 = (MEM_READ & s23);
  // DATA_ROM
  DIG_ROM_16384X16_DATA_ROM DIG_ROM_16384X16_DATA_ROM_i5 (
    .A( s6 ),
    .sel( s7 ),
    .D( s8 )
  );
  PriorityEncoder2 PriorityEncoder2_i6 (
    .in0( 1'b0 ),
    .in1( s12 ),
    .in2( s7 ),
    .in3( s31 ),
    .num( s34 )
  );
  // MDR
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i7 (
    .D( MEM_OUT_BUS_temp ),
    .C( CPU_CLK ),
    .en( MDR_LOAD ),
    .Q( s5 )
  );
  // RAM
  DIG_RAMDualPort #(
    .Bits(16),
    .AddrBits(15)
  )
  DIG_RAMDualPort_i8 (
    .A( s9 ),
    .Din( s10 ),
    .str( s11 ),
    .C( CPU_CLK ),
    .ld( s12 ),
    .D( s13 )
  );
  // GPIO_PORT1
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i9 (
    .D( s10 ),
    .C( CPU_CLK ),
    .en( s14 ),
    .Q( s15 )
  );
  // GPIO_PORT2
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i10 (
    .D( s10 ),
    .C( CPU_CLK ),
    .en( s16 ),
    .Q( s17 )
  );
  // GPIO_PORT3
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i11 (
    .D( s10 ),
    .C( CPU_CLK ),
    .en( s18 ),
    .Q( s19 )
  );
  // GPIO_PORT4
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i12 (
    .D( s10 ),
    .C( CPU_CLK ),
    .en( s20 ),
    .Q( s21 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i13 (
    .sel( s26 ),
    .in_0( port4_temp ),
    .in_1( port3_temp ),
    .in_2( port2_temp ),
    .in_3( port1_temp ),
    .out( s30 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i14 (
    .sel( s31 ),
    .in_0( 16'b0 ),
    .in_1( s30 ),
    .out( s32 )
  );
  DriverInvBus #(
    .Bits(16)
  )
  DriverInvBus_i15 (
    .in( s17 ),
    .sel( MEM_READ ),
    .out( port3_temp )
  );
  DriverInvBus #(
    .Bits(16)
  )
  DriverInvBus_i16 (
    .in( s19 ),
    .sel( MEM_READ ),
    .out( port2_temp )
  );
  DriverInvBus #(
    .Bits(16)
  )
  DriverInvBus_i17 (
    .in( s15 ),
    .sel( MEM_READ ),
    .out( port4_temp )
  );
  DriverInvBus #(
    .Bits(16)
  )
  DriverInvBus_i18 (
    .in( s21 ),
    .sel( MEM_READ ),
    .out( port1_temp )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i19 (
    .sel( MEM_DATA_SEL ),
    .in_0( RA ),
    .in_1( RB ),
    .in_2( s33 ),
    .in_3( s5 ),
    .out( s10 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i20 (
    .sel( s34 ),
    .in_0( 16'b0 ),
    .in_1( s13 ),
    .in_2( s8 ),
    .in_3( s32 ),
    .out( MEM_OUT_BUS_temp )
  );
  assign MEM_OUT_BUS = MEM_OUT_BUS_temp;
  assign port1 = port1_temp;
  assign port2 = port2_temp;
  assign port3 = port3_temp;
  assign port4 = port4_temp;
endmodule
