/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_ROM_65536X16_INSTRUCTION_ROM (
    input [15:0] A,
    input sel,
    output reg [15:0] D
);
    reg [15:0] my_rom [0:18];

    always @ (*) begin
        if (~sel)
            D = 16'hz;
        else if (A > 16'h12)
            D = 16'h0;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 16'h7088;
        my_rom[1] = 16'h700;
        my_rom[2] = 16'h8f;
        my_rom[3] = 16'h400;
        my_rom[4] = 16'h24;
        my_rom[5] = 16'h70ec;
        my_rom[6] = 16'h100;
        my_rom[7] = 16'hf7;
        my_rom[8] = 16'h200;
        my_rom[9] = 16'hf088;
        my_rom[10] = 16'h500;
        my_rom[11] = 16'h108f;
        my_rom[12] = 16'h200;
        my_rom[13] = 16'h9024;
        my_rom[14] = 16'hf0ec;
        my_rom[15] = 16'h300;
        my_rom[16] = 16'h10f7;
        my_rom[17] = 16'h400;
        my_rom[18] = 16'h70ff;
    end
endmodule


module PROG_MEMORY (
  input [15:0] PC_OUT,
  output [15:0] PROG_ROM
);
  // INSTRUCTION_ROM
  DIG_ROM_65536X16_INSTRUCTION_ROM DIG_ROM_65536X16_INSTRUCTION_ROM_i0 (
    .A( PC_OUT ),
    .sel( 1'b1 ),
    .D( PROG_ROM )
  );
endmodule
