/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Demux3
#(
    parameter Default = 0 
)
(
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    output out_4,
    output out_5,
    output out_6,
    output out_7,
    input [2:0] sel,
    input in
);
    assign out_0 = (sel == 3'h0)? in : Default;
    assign out_1 = (sel == 3'h1)? in : Default;
    assign out_2 = (sel == 3'h2)? in : Default;
    assign out_3 = (sel == 3'h3)? in : Default;
    assign out_4 = (sel == 3'h4)? in : Default;
    assign out_5 = (sel == 3'h5)? in : Default;
    assign out_6 = (sel == 3'h6)? in : Default;
    assign out_7 = (sel == 3'h7)? in : Default;
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Mux_8x1_NBits #(
    parameter Bits = 2
)
(
    input [2:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    input [(Bits - 1):0] in_4,
    input [(Bits - 1):0] in_5,
    input [(Bits - 1):0] in_6,
    input [(Bits - 1):0] in_7,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            3'h0: out = in_0;
            3'h1: out = in_1;
            3'h2: out = in_2;
            3'h3: out = in_3;
            3'h4: out = in_4;
            3'h5: out = in_5;
            3'h6: out = in_6;
            3'h7: out = in_7;
            default:
                out = 'h0;
        endcase
    end
endmodule


module REG_BANK (
  input [2:0] REG_A,
  input CLK,
  input [2:0] REG_B,
  input A_RW,
  input B_RW,
  input [15:0] DATA_IN,
  output [15:0] RA,
  output [15:0] RB
);
  wire s0;
  wire [15:0] s1;
  wire s2;
  wire [15:0] s3;
  wire s4;
  wire [15:0] s5;
  wire s6;
  wire [15:0] s7;
  wire s8;
  wire [15:0] s9;
  wire s10;
  wire [15:0] s11;
  wire s12;
  wire [15:0] s13;
  wire s14;
  wire [15:0] s15;
  wire s16;
  wire [15:0] s17;
  wire s18;
  wire [15:0] s19;
  wire s20;
  wire [15:0] s21;
  wire s22;
  wire [15:0] s23;
  wire s24;
  wire [15:0] s25;
  wire s26;
  wire [15:0] s27;
  wire s28;
  wire [15:0] s29;
  wire s30;
  wire [15:0] s31;
  Demux3 #(
    .Default(0)
  )
  Demux3_i0 (
    .sel( REG_A ),
    .in( A_RW ),
    .out_0( s0 ),
    .out_1( s2 ),
    .out_2( s4 ),
    .out_3( s6 ),
    .out_4( s8 ),
    .out_5( s10 ),
    .out_6( s12 ),
    .out_7( s14 )
  );
  Demux3 #(
    .Default(0)
  )
  Demux3_i1 (
    .sel( REG_B ),
    .in( B_RW ),
    .out_0( s16 ),
    .out_1( s18 ),
    .out_2( s20 ),
    .out_3( s22 ),
    .out_4( s24 ),
    .out_5( s26 ),
    .out_6( s28 ),
    .out_7( s30 )
  );
  // A0
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i2 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s0 ),
    .Q( s1 )
  );
  // A1
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i3 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s2 ),
    .Q( s3 )
  );
  // A2
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i4 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s4 ),
    .Q( s5 )
  );
  // A3
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i5 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s6 ),
    .Q( s7 )
  );
  // A4
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i6 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s8 ),
    .Q( s9 )
  );
  // A5
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i7 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s10 ),
    .Q( s11 )
  );
  // A6
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i8 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s12 ),
    .Q( s13 )
  );
  // A7
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i9 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s14 ),
    .Q( s15 )
  );
  // B0
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i10 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s16 ),
    .Q( s17 )
  );
  // B1
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i11 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s18 ),
    .Q( s19 )
  );
  // B2
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i12 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s20 ),
    .Q( s21 )
  );
  // B3
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i13 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s22 ),
    .Q( s23 )
  );
  // B4
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i14 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s24 ),
    .Q( s25 )
  );
  // B5
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i15 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s26 ),
    .Q( s27 )
  );
  // B6
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i16 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s28 ),
    .Q( s29 )
  );
  // B7
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i17 (
    .D( DATA_IN ),
    .C( CLK ),
    .en( s30 ),
    .Q( s31 )
  );
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i18 (
    .sel( REG_A ),
    .in_0( s1 ),
    .in_1( s3 ),
    .in_2( s5 ),
    .in_3( s7 ),
    .in_4( s9 ),
    .in_5( s11 ),
    .in_6( s13 ),
    .in_7( s15 ),
    .out( RA )
  );
  Mux_8x1_NBits #(
    .Bits(16)
  )
  Mux_8x1_NBits_i19 (
    .sel( REG_B ),
    .in_0( s17 ),
    .in_1( s19 ),
    .in_2( s21 ),
    .in_3( s23 ),
    .in_4( s25 ),
    .in_5( s27 ),
    .in_6( s29 ),
    .in_7( s31 ),
    .out( RB )
  );
endmodule
