/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module SPECIAL_MUL (
  input Z,
  input [5:0] OPCODE,
  input uSTEP_RESET,
  input RA_BIT0,
  input [15:0] RB,
  input CLK,
  input [5:0] uSTEP,
  output MUL_CTRL,
  output [15:0] MUL_RESULT
);
  wire s0;
  wire [15:0] s1;
  wire [15:0] MUL_RESULT_temp;
  wire [15:0] s2;
  wire [15:0] s3;
  assign MUL_CTRL = ((Z & (~ OPCODE[0] & ~ OPCODE[1] & ~ OPCODE[2] & OPCODE[3] & ~ OPCODE[4] & ~ OPCODE[5])) & uSTEP_RESET);
  assign s0 = ((uSTEP[0] & uSTEP[1] & ~ uSTEP[2] & ~ uSTEP[3] & ~ uSTEP[4] & ~ uSTEP[5]) & RA_BIT0);
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i0 (
    .sel( s0 ),
    .in_0( 16'b0 ),
    .in_1( RB ),
    .out( s1 )
  );
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i1 (
    .a( s1 ),
    .b( MUL_RESULT_temp ),
    .c_i( 1'b0 ),
    .s( s2 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i2 (
    .sel( uSTEP_RESET ),
    .in_0( s2 ),
    .in_1( 16'b0 ),
    .out( s3 )
  );
  // MUL_RESULT
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i3 (
    .D( s3 ),
    .C( CLK ),
    .en( 1'b1 ),
    .Q( MUL_RESULT_temp )
  );
  assign MUL_RESULT = MUL_RESULT_temp;
endmodule
