/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module SPECIAL_DIV (
  input N,
  input [5:0] OPCODE,
  input uSTEP_RESET,
  input [5:0] uSTEP,
  input CLK,
  output DIV_CTRL,
  output [15:0] DIV_RESULT
);
  wire [15:0] s0;
  wire [15:0] DIV_RESULT_temp;
  wire [15:0] s1;
  wire [15:0] s2;
  assign DIV_CTRL = (N & (OPCODE[0] & ~ OPCODE[1] & ~ OPCODE[2] & OPCODE[3] & ~ OPCODE[4] & ~ OPCODE[5]));
  assign s0[0] = (~ uSTEP[0] & ~ uSTEP[1] & uSTEP[2] & ~ uSTEP[3] & ~ uSTEP[4] & ~ uSTEP[5]);
  assign s0[15:1] = 15'b0;
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i0 (
    .a( s0 ),
    .b( DIV_RESULT_temp ),
    .c_i( 1'b0 ),
    .s( s1 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i1 (
    .sel( uSTEP_RESET ),
    .in_0( s1 ),
    .in_1( 16'b0 ),
    .out( s2 )
  );
  // DIV_RESULT
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i2 (
    .D( s2 ),
    .C( CLK ),
    .en( 1'b1 ),
    .Q( DIV_RESULT_temp )
  );
  assign DIV_RESULT = DIV_RESULT_temp;
endmodule
