/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module Mux_4x1_NBits #(
    parameter Bits = 2
)
(
    input [1:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    input [(Bits - 1):0] in_2,
    input [(Bits - 1):0] in_3,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            2'h0: out = in_0;
            2'h1: out = in_1;
            2'h2: out = in_2;
            2'h3: out = in_3;
            default:
                out = 'h0;
        endcase
    end
endmodule


module WB_SELECTOR (
  input [15:0] MEM_OUTBUS,
  input [15:0] ALU_OUT,
  input [15:0] DIV_RESULT,
  input [15:0] MUL_RESULT,
  input [15:0] IMM_OUT,
  input [15:0] PC_OUT,
  input DIV_CTRL,
  input MUL_CTRL,
  input [1:0] WB_SEL,
  output [15:0] DATA_IN
);
  wire [15:0] s0;
  wire [15:0] s1;
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i0 (
    .sel( DIV_CTRL ),
    .in_0( ALU_OUT ),
    .in_1( DIV_RESULT ),
    .out( s0 )
  );
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i1 (
    .sel( MUL_CTRL ),
    .in_0( s0 ),
    .in_1( MUL_RESULT ),
    .out( s1 )
  );
  Mux_4x1_NBits #(
    .Bits(16)
  )
  Mux_4x1_NBits_i2 (
    .sel( WB_SEL ),
    .in_0( MEM_OUTBUS ),
    .in_1( s1 ),
    .in_2( IMM_OUT ),
    .in_3( PC_OUT ),
    .out( DATA_IN )
  );
endmodule
